# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
Plane.create(:name => "Bearclaw-P", :unlock_level => 1)
Plane.create(:name => "Bearclaw-C", :unlock_level => 1)
Plane.create(:name => "Griffon-P", :unlock_level => 1)
Plane.create(:name => "Griffon-C", :unlock_level => 1)
Plane.create(:name => "Navigator-P", :unlock_level => 1)
Plane.create(:name => "Navigator-M", :unlock_level => 1)
Plane.create(:name => "Navigator-C", :unlock_level => 1)
Plane.create(:name => "Wallaby-P", :unlock_level => 1)
Plane.create(:name => "Wallaby-M", :unlock_level => 1)
Plane.create(:name => "Wallaby-C", :unlock_level => 1)
Plane.create(:name => "Supergopher-P", :unlock_level => 4)
Plane.create(:name => "Supergopher-C", :unlock_level => 4)
Plane.create(:name => "Airvan-P", :unlock_level => 5)
Plane.create(:name => "Airvan-M", :unlock_level => 5)
Plane.create(:name => "Airvan-C", :unlock_level => 5)
Plane.create(:name => "Anan-P", :unlock_level => 6)
Plane.create(:name => "Anan-M", :unlock_level => 6)
Plane.create(:name => "Anan-C", :unlock_level => 6)
Plane.create(:name => "Kangaroo-P", :unlock_level => 7)
Plane.create(:name => "Kangaroo-M", :unlock_level => 7)
Plane.create(:name => "Kangaroo-C", :unlock_level => 7)
Plane.create(:name => "Mohawk-P", :unlock_level => 8)
Plane.create(:name => "Mohawk-M", :unlock_level => 8)
Plane.create(:name => "Mohawk-C", :unlock_level => 8)
Plane.create(:name => "Birchcraft-P", :unlock_level => 10)
Plane.create(:name => "Birchcraft-M", :unlock_level => 10)
Plane.create(:name => "Birchcraft-C", :unlock_level => 10)
Plane.create(:name => "Equinox-P", :unlock_level => 12)
Plane.create(:name => "Equinox-M", :unlock_level => 12)
Plane.create(:name => "Equinox-C", :unlock_level => 12)
Plane.create(:name => "Pearjet-P", :unlock_level => 14)
Plane.create(:name => "Pearjet-M", :unlock_level => 14)
Plane.create(:name => "Pearjet-C", :unlock_level => 14)
Plane.create(:name => "Aeroeagle-P", :unlock_level => 16)
Plane.create(:name => "Aeroeagle-M", :unlock_level => 16)
Plane.create(:name => "Aeroeagle-C", :unlock_level => 16)
Plane.create(:name => "Fogbuster-P", :unlock_level => 20)
Plane.create(:name => "Fogbuster-M", :unlock_level => 20)
Plane.create(:name => "Fogbuster-C", :unlock_level => 20)
Plane.create(:name => "Sequoia-P", :unlock_level => 22)
Plane.create(:name => "Sequoia-M", :unlock_level => 22)
Plane.create(:name => "Sequoia-C", :unlock_level => 22)
Plane.create(:name => "Tetra-P", :unlock_level => 24)
Plane.create(:name => "Tetra-M", :unlock_level => 24)
Plane.create(:name => "Tetra-C", :unlock_level => 24)
Plane.create(:name => "Cyclone-P", :unlock_level => 26)
Plane.create(:name => "Cyclone-M", :unlock_level => 26)
Plane.create(:name => "Cyclone-C", :unlock_level => 26)
Plane.create(:name => "Cloudliner-P", :unlock_level => 28)
Plane.create(:name => "Cloudliner-M", :unlock_level => 28)
Plane.create(:name => "Cloudliner-C", :unlock_level => 28)

Part.create(:name => "Controls")
Part.create(:name => "Engine")
Part.create(:name => "Body")